### ISSUE TITLE
Erro ao pesquisar CEP

### ISSUE THREAD

**Issue by anderson-costa-t2b** [farukaf/BrasilAPI-DotNet#10]
Olá, boa noite!

A chamada:
https://brasilapi.com.br/api/cep/v2/09726121

Retorna o erro abaixo:
{
    "message": "invalid json response body at https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&country=Brasil&state=SP&city=S%C3%A3o%20Bernardo%20do%20Campo&street=Rua%20Domiciano%20Rossi%20(Jd%20Ch%20Inglesa) reason: Unexpected token < in JSON at position 0",
    "type": "invalid-json"
}

**Comment by farukaf** [comment]
Dado que os dados vem de outros serviços pode ser que estava com algum tipo de instabilidade na epoca...
