### ISSUE TITLE
Sugestão de implementação

### ISSUE THREAD

**Issue by LorhanSohaky** [farukaf/BrasilAPI-DotNet#2]
Imagino que você tenha escrito todo o código, mas se quiser dá para gerar a lib de maneira mais simplificada. Como a documentação é feita usando swagger dá para tentar usar um [swagger-codegen](https://swagger.io/tools/swagger-codegen/) para gerar a biblioteca automaticamente.

E se quiser acho que é possível deixar mais automático, pode tentar configurar este repo para ficar ouvindo as alterações do repo oficial e toda vez que tiver um novo commit na master você gera uma nova versão da lib por meio do github action

**Comment by farukaf** [comment]
@LorhanSohaky 
Sim é possível implementar, teria que ver o impacto no caso de retro-compatibilidade... 
Eu não consegui achar o swagger que gera a doc... inclusive abri uma issue como esta diferente o nome da propriedade respondida com o da documentação.

**Comment by LorhanSohaky** [comment]
Como assim retrocompatibilidade? Imagino que esse codegen deva gerar um método `.v1.rotaX(parametros)`

Creio que a saída dessa função gere um json aceito pelo swagger

https://github.com/BrasilAPI/BrasilAPI/blob/c3ecd96ecdc2e4f317e02429c1a74b69063128f6/services/getJsonDoc.js#L7
