### ISSUE TITLE
Parsing de JSON com System.Text.Json

### ISSUE THREAD

**Issue by HClausing** [farukaf/BrasilAPI-DotNet#7]
Olá a todos.

Parabéns pelo excelente trabalho realizado.

Gostaria de propor a mudança da dependência Newtonsoft.Json para System.Text.Json nativo do .NET.

Cabe ressaltar que esta implementação não seria compatível com .NET Standart, se vier a ser considerada.

**Comment by farukaf** [comment]
Eu lembro que tentei na epoca, mas não consegui deixar a resposta dinamica.
Mas confesso que não tentei muito.
Vou deixar a issue aberta pra voltar nisso quando possivel...

**Comment by farukaf** [comment]
Quanto a ser compativel com .net standard, tenho minhs duvidas, eu cheguei a utilizar com um projeto xamarin na epoca que criei.
Mas é um passo importante por vários outros motivos.

**Comment by HClausing** [comment]
Posso fazer os testes nesta proposta assim que conseguir um tempo, se houver interesse dos mantenedores.

Havendo êxito abro a PR para apreciação.

**Comment by farukaf** [comment]
Foi feito o PR para remoção... se quiser testar a versão da PR ou a versão atual fica a vontade. 
pensei em adicionar a versão com xamarin como exemplo
mas tempo tem sido um problema 😅
