### ISSUE TITLE
ISBN endpoint

### ISSUE THREAD

**Issue by ArthurDotSaito** [farukaf/BrasilAPI-DotNet#8]
Olá! Parabéns pelo excelente trabalho!

Gostaria de informar que o projeto oficial agora inclui um endpoint para ISBN, que fornece várias informações sobre livros a partir do número ISBN. Não tenho certeza se essa funcionalidade foi adicionada recentemente ou se existe algum motivo específico para que ela não estivesse disponível antes.

Essa issue tem mais o objetivo de informar do que qualquer outra coisa, considerando que a implementação desse endpoint parece ser relativamente simples.

Abç

**Comment by farukaf** [comment]
Opa, assim que possível...

**Comment by farukaf** [comment]
@jndeus fez um PR e eu mergiei... vou subir na proxima versão
